// <auto-generated />
namespace PetHotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class PriceCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriceCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201411071020421_PriceCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
